export default {
  SET_LOADING_HANG_GPLX: "SET_LOADING_HANG_GPLX",
  CREATE_HANG_GPLX: "CREATE_HANG_GPLX",
  GET_ALL_HANG_GPLX: "GET_ALL_HANG_GPLX",
  GET_BY_ID_HANG_GPLX: "GET_BY_ID_HANG_GPLX",
  UPDATE_HANG_GPLX: "UPDATE_HANG_GPLX",
};
