export default {                                                         
  SET_LOADING_KETQUADAOTAO: "SET_LOADING_KETQUADAOTAO",  
  CREATE_KETQUADAOTAO: "CREATE_KETQUADAOTAO",            
  GET_ALL_KETQUADAOTAO: "GET_ALL_KETQUADAOTAO",
  GET_ALL_COMBOBOX_KHOAHOC:'GET_ALL_COMBOBOX_KHOAHOC', 
  GET_BY_ID_KETQUACHINHCHI: "GET_BY_ID_KETQUACHINHCHI",     
  GET_BY_ID_KETQUADAOTAO: "GET_BY_ID_KETQUADAOTAO",          
  UPDATE_KETQUADAOTAO: "UPDATE_KETQUADAOTAO",
  GET_LIST_MONHOC_DAOTAO:"GET_LIST_MONHOC_DAOTAO",
  GET_LIST_MONHOC:'GET_LIST_MONHOC',
};                                                                       
