export default { 
  SET_LOADING_DONVIHANHCHINH: "SET_LOADING_DONVIHANHCHINH",  
  CREATE_DONVIHANHCHINH: "CREATE_DONVIHANHCHINH",            
  GET_ALL_DONVIHANHCHINH: "GET_ALL_DONVIHANHCHINH",
  GET_ALL_COMBOBOX_DVHC: "GET_ALL_COMBOBOX_DVHC",   
  GET_ID_DONVIHANHCHINH:'GET_ID_DONVIHANHCHINH',
  GET_BY_ID_DONVIHANHCHINH: "GET_BY_ID_DONVIHANHCHINH",          
  UPDATE_DONVIHANHCHINH: "UPDATE_DONVIHANHCHINH",     
};                                                                       
