export default {                                                         
  SET_LOADING_KETQUASATHACH: "SET_LOADING_KETQUASATHACH",  
  CREATE_KETQUASATHACH: "CREATE_KETQUASATHACH",            
  GET_ALL_KETQUASATHACH: "GET_ALL_KETQUASATHACH",          
  GET_BY_ID_KETQUASATHACH: "GET_BY_ID_KETQUASATHACH",          
  UPDATE_KETQUASATHACH: "UPDATE_KETQUASATHACH",
  GET_COMBOBOX_KYSATHACH:"GET_COMBOBOX_KYSATHACH",
  GET_ID_DIEMLYTHUYET_SATHACH:"GET_ID_DIEMLYTHUYET_SATHACH",        
};                                                                       
