export default {
  SET_LOADING_GIAO_VIEN: "SET_LOADING_GIAO_VIEN",
  CREATE_GIAO_VIEN: "CREATE_GIAO_VIEN",
  GET_ALL_GIAO_VIEN :"GET_ALL_GIAO_VIEN",
  GET_BY_ID_GIAO_VIEN: "GET_BY_ID_GIAO_VIEN",
  EXPORT_GIAO_VIEN : "EXPORT_GIAO_VIEN",
  GET_NOI_CAP:"GET_NOI_CAP",
  GET_HANG_GPLX:"GET_HANG_GPLX",
  CREATE_GPLX_GV:"CREATE_GPLX_GV",
  UPDATE_VIEW_GPLX_GV:"UPDATE_VIEW_GPLX_GV",
  UPDATE_GPLX_GV:"UPDATE_GPLX_GV",
  CLEAR_GPLX_GV:"CLEAR_GPLX_GV",
  UPDATE_GV : "UPDATE_GV"
};
