export default {
  SET_LOADING_TT_KE_TOAN: "SET_LOADING_TT_KE_TOAN",
  CREATE_TT_KE_TOAN: "CREATE_TT_KE_TOAN",
  GET_ALL_TT_KE_TOAN_GV: "GET_ALL_TT_KE_TOAN_GV",
  GET_ALL_TT_KE_TOAN_NV: "GET_ALL_TT_KE_TOAN_NV",
  GET_BY_ID_TT_KE_TOAN: "GET_BY_ID_TT_KE_TOAN",
  UPDATE_TT_KE_TOAN: "UPDATE_TT_KE_TOAN",
};
