export default {
  SET_LOADING_XE: "SET_LOADING_XE",
  CREATE_XE: "CREATE_XE",
  GET_ALL_XE: "GET_ALL_XE",
  GET_BY_ID_XE: "GET_BY_ID_XE",
  GET_LOAI_XE: " GET_LOAI_XE",
  GET_LOAI_NHIEN_LIEU: " GET_LOAI_NHIEN_LIEU",
  UPDATE_XE: "UPDATE_XE",
  GET_GIAO_VIEN: "GET_GIAO_VIEN",
  EXPORT_XE : "EXPORT_XE"
};
