export default {
  SET_LOADING_MON_HOC: "SET_LOADING_MON_HOC",
  CREATE_MON_HOC: "CREATE_MON_HOC",
  GET_ALL_MON_HOC: "GET_ALL_MON_HOC",
  GET_BY_ID_MON_HOC: "GET_BY_ID_MON_HOC",
  UPDATE_MON_HOC: "UPDATE_MON_HOC",
};
